import type {
  Patient,
  Bed,
  ClinicalContext,
  LaboratoryResult,
} from '@aegispulse/types';
import type { GroundTruthVitals } from './ground-truth';

export interface PatientProfile {
  patient: Patient;
  bed: Bed;
  baselineVitals: GroundTruthVitals;
  clinicalContext: ClinicalContext;
  initialLabs: LaboratoryResult[];
  clinicalNarrative: string;
}

const REFERENCE_SHIFT_START = 1773471600000; // Reference date 07:00:00

export const SIX_WARD_PATIENT_PROFILES: readonly PatientProfile[] = [
  // --------------------------------------------------------------------------
  // Bed 401: Stable Post-Op Patient
  // --------------------------------------------------------------------------
  {
    patient: {
      id: 'P001',
      mrn: 'MRN-40101',
      name: 'Ananya Ramanathan',
      age: 42,
      gender: 'FEMALE',
      wardId: 'WARD-4B',
      bedId: 'BED-401',
      bedNumber: '401-A',
      admissionDiagnosis: 'Post-Op Day 1: Laparoscopic Cholecystectomy',
      admissionTimestamp: REFERENCE_SHIFT_START - 86400000,
      attendingPhysician: 'Dr. Sarah Lin, MD',
      primaryNurse: 'Nurse Rachel Hayes, RN',
      codeStatus: 'FULL_CODE',
      baselineMEWS: 0,
      allergies: ['Penicillin'],
      isolationStatus: 'NONE',
      isActive: true,
      history: ['Mild asthma (well-controlled)', 'No prior surgical complications'],
    },
    bed: {
      id: 'BED-401',
      bedNumber: '401-A',
      wardId: 'WARD-4B',
      roomNumber: '401',
      status: 'OCCUPIED',
      currentPatientId: 'P001',
      cameraDeviceId: 'CAM-RPPG-401',
    },
    baselineVitals: {
      heartRate: 72,
      respiratoryRate: 15,
      systolicBP: 118,
      diastolicBP: 76,
      bodyTemperature: 36.8,
      oxygenSaturation: 98,
      hrvRmssd: 42,
      shockIndex: 0.61, // 72 / 118
    },
    clinicalContext: {
      id: 'CTX-P001',
      patientId: 'P001',
      admissionReason: 'Elective Laparoscopic Cholecystectomy',
      postOpDay: 1,
      comorbidities: ['Mild Asthma'],
      codeStatus: 'FULL_CODE',
      oxygenDelivery: 'ROOM_AIR',
      isolationStatus: 'NONE',
      baselineMEWS: 0,
      updatedAt: REFERENCE_SHIFT_START,
    },
    initialLabs: [
      {
        id: 'LAB-P001-LAC',
        patientId: 'P001',
        timestamp: REFERENCE_SHIFT_START - 7200000,
        testCode: 'LACTATE',
        testName: 'Venous Lactate',
        value: 1.1,
        unit: 'MMOL_PER_L',
        referenceRange: { low: 0.5, high: 2.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
      {
        id: 'LAB-P001-WBC',
        patientId: 'P001',
        timestamp: REFERENCE_SHIFT_START - 7200000,
        testCode: 'WBC',
        testName: 'White Blood Cell Count',
        value: 7.2,
        unit: 'X10_9_PER_L',
        referenceRange: { low: 4.0, high: 11.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
    ],
    clinicalNarrative: 'Standard surgical post-op recovery. Unremarkable post-anesthesia trajectory.',
  },

  // --------------------------------------------------------------------------
  // Bed 402: COPD Patient with Baseline Tachypnea & Supplemental O2
  // --------------------------------------------------------------------------
  {
    patient: {
      id: 'P002',
      mrn: 'MRN-40202',
      name: 'Robert Chen',
      age: 68,
      gender: 'MALE',
      wardId: 'WARD-4B',
      bedId: 'BED-402',
      bedNumber: '402-A',
      admissionDiagnosis: 'Acute Exacerbation of Chronic Obstructive Pulmonary Disease',
      admissionTimestamp: REFERENCE_SHIFT_START - 172800000,
      attendingPhysician: 'Dr. Michael Sterling, MD',
      primaryNurse: 'Nurse Rachel Hayes, RN',
      codeStatus: 'FULL_CODE',
      baselineMEWS: 2,
      allergies: ['Sulfa drugs'],
      isolationStatus: 'NONE',
      isActive: true,
      history: ['COPD GOLD Stage III', 'Coronary Artery Disease', 'Tobacco use (40 pack-years)'],
    },
    bed: {
      id: 'BED-402',
      bedNumber: '402-A',
      wardId: 'WARD-4B',
      roomNumber: '402',
      status: 'OCCUPIED',
      currentPatientId: 'P002',
      cameraDeviceId: 'CAM-RPPG-402',
    },
    baselineVitals: {
      heartRate: 86,
      respiratoryRate: 20,
      systolicBP: 132,
      diastolicBP: 82,
      bodyTemperature: 37.1,
      oxygenSaturation: 93,
      hrvRmssd: 26,
      shockIndex: 0.65, // 86 / 132
    },
    clinicalContext: {
      id: 'CTX-P002',
      patientId: 'P002',
      admissionReason: 'COPD Exacerbation with Purulent Sputum',
      comorbidities: ['COPD', 'CAD', 'Hypertension'],
      codeStatus: 'FULL_CODE',
      oxygenDelivery: 'NASAL_CANNULA',
      o2FlowRateLpm: 2.0,
      isolationStatus: 'NONE',
      baselineMEWS: 2,
      updatedAt: REFERENCE_SHIFT_START,
    },
    initialLabs: [
      {
        id: 'LAB-P002-LAC',
        patientId: 'P002',
        timestamp: REFERENCE_SHIFT_START - 10800000,
        testCode: 'LACTATE',
        testName: 'Venous Lactate',
        value: 1.6,
        unit: 'MMOL_PER_L',
        referenceRange: { low: 0.5, high: 2.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
      {
        id: 'LAB-P002-WBC',
        patientId: 'P002',
        timestamp: REFERENCE_SHIFT_START - 10800000,
        testCode: 'WBC',
        testName: 'White Blood Cell Count',
        value: 11.4,
        unit: 'X10_9_PER_L',
        referenceRange: { low: 4.0, high: 11.0 },
        isCritical: true,
        sourceLab: 'Central Hospital Lab',
      },
    ],
    clinicalNarrative: 'Chronic baseline respiratory elevation. Relies on 2L nasal cannula to maintain 92-94% SpO2.',
  },

  // --------------------------------------------------------------------------
  // Bed 403: Frail Post-Op Orthopedic Patient (Occult Shock / Sepsis Risk)
  // --------------------------------------------------------------------------
  {
    patient: {
      id: 'P003',
      mrn: 'MRN-40303',
      name: 'Eleanor Vance',
      age: 79,
      gender: 'FEMALE',
      wardId: 'WARD-4B',
      bedId: 'BED-403',
      bedNumber: '403-A',
      admissionDiagnosis: 'Post-Op Day 2: Femur Fracture Repair (ORIF)',
      admissionTimestamp: REFERENCE_SHIFT_START - 129600000,
      attendingPhysician: 'Dr. Sarah Lin, MD',
      primaryNurse: 'Nurse Rachel Hayes, RN',
      codeStatus: 'FULL_CODE',
      baselineMEWS: 1,
      allergies: ['Latex'],
      isolationStatus: 'NONE',
      isActive: true,
      history: ['Osteoporosis', 'Chronic Kidney Disease Stage 2', 'Atrial Fibrillation'],
    },
    bed: {
      id: 'BED-403',
      bedNumber: '403-A',
      wardId: 'WARD-4B',
      roomNumber: '403',
      status: 'OCCUPIED',
      currentPatientId: 'P003',
      cameraDeviceId: 'CAM-RPPG-403',
    },
    baselineVitals: {
      heartRate: 78,
      respiratoryRate: 16,
      systolicBP: 114,
      diastolicBP: 68,
      bodyTemperature: 37.3,
      oxygenSaturation: 96,
      hrvRmssd: 22,
      shockIndex: 0.68, // 78 / 114
    },
    clinicalContext: {
      id: 'CTX-P003',
      patientId: 'P003',
      admissionReason: 'Right Femur Neck Fracture s/p Mechanical Fall',
      postOpDay: 2,
      comorbidities: ['Osteoporosis', 'Atrial Fibrillation', 'CKD Stage 2'],
      codeStatus: 'FULL_CODE',
      oxygenDelivery: 'ROOM_AIR',
      isolationStatus: 'NONE',
      baselineMEWS: 1,
      updatedAt: REFERENCE_SHIFT_START,
    },
    initialLabs: [
      {
        id: 'LAB-P003-LAC',
        patientId: 'P003',
        timestamp: REFERENCE_SHIFT_START - 14400000,
        testCode: 'LACTATE',
        testName: 'Venous Lactate',
        value: 1.8,
        unit: 'MMOL_PER_L',
        referenceRange: { low: 0.5, high: 2.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
      {
        id: 'LAB-P003-WBC',
        patientId: 'P003',
        timestamp: REFERENCE_SHIFT_START - 14400000,
        testCode: 'WBC',
        testName: 'White Blood Cell Count',
        value: 10.8,
        unit: 'X10_9_PER_L',
        referenceRange: { low: 4.0, high: 11.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
    ],
    clinicalNarrative: 'Elderly orthopedic post-op patient. Vulnerable to occult retroperitoneal or wound bleeding and post-op delirium.',
  },

  // --------------------------------------------------------------------------
  // Bed 404: Acute Pancreatitis Patient (Day 3 Recovery)
  // --------------------------------------------------------------------------
  {
    patient: {
      id: 'P004',
      mrn: 'MRN-40404',
      name: 'Marcus Davies',
      age: 55,
      gender: 'MALE',
      wardId: 'WARD-4B',
      bedId: 'BED-404',
      bedNumber: '404-B',
      admissionDiagnosis: 'Acute Gallstone Pancreatitis (Day 3)',
      admissionTimestamp: REFERENCE_SHIFT_START - 216000000,
      attendingPhysician: 'Dr. Michael Sterling, MD',
      primaryNurse: 'Nurse Rachel Hayes, RN',
      codeStatus: 'FULL_CODE',
      baselineMEWS: 1,
      allergies: [],
      isolationStatus: 'NONE',
      isActive: true,
      history: ['Hypertriglyceridemia', 'Type 2 Diabetes Mellitus'],
    },
    bed: {
      id: 'BED-404',
      bedNumber: '404-B',
      wardId: 'WARD-4B',
      roomNumber: '404',
      status: 'OCCUPIED',
      currentPatientId: 'P004',
      cameraDeviceId: 'CAM-RPPG-404',
    },
    baselineVitals: {
      heartRate: 82,
      respiratoryRate: 17,
      systolicBP: 124,
      diastolicBP: 78,
      bodyTemperature: 37.2,
      oxygenSaturation: 97,
      hrvRmssd: 34,
      shockIndex: 0.66,
    },
    clinicalContext: {
      id: 'CTX-P004',
      patientId: 'P004',
      admissionReason: 'Acute Epigastric Pain, Lipase 1800 U/L',
      comorbidities: ['Type 2 Diabetes', 'Hypertriglyceridemia'],
      codeStatus: 'FULL_CODE',
      oxygenDelivery: 'ROOM_AIR',
      isolationStatus: 'NONE',
      baselineMEWS: 1,
      updatedAt: REFERENCE_SHIFT_START,
    },
    initialLabs: [
      {
        id: 'LAB-P004-LAC',
        patientId: 'P004',
        timestamp: REFERENCE_SHIFT_START - 18000000,
        testCode: 'LACTATE',
        testName: 'Venous Lactate',
        value: 1.4,
        unit: 'MMOL_PER_L',
        referenceRange: { low: 0.5, high: 2.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
    ],
    clinicalNarrative: 'Responding well to conservative hydration and analgesia. Abdominal pain decreasing.',
  },

  // --------------------------------------------------------------------------
  // Bed 405: Step-Down Telemetry Patient (Cardiac Post-Op / Motion Prone)
  // --------------------------------------------------------------------------
  {
    patient: {
      id: 'P005',
      mrn: 'MRN-40505',
      name: 'Sunita Patel',
      age: 61,
      gender: 'FEMALE',
      wardId: 'WARD-4B',
      bedId: 'BED-405',
      bedNumber: '405-A',
      admissionDiagnosis: 'Post-CABG Step-Down (Post-Op Day 4)',
      admissionTimestamp: REFERENCE_SHIFT_START - 345600000,
      attendingPhysician: 'Dr. Sarah Lin, MD',
      primaryNurse: 'Nurse Rachel Hayes, RN',
      codeStatus: 'FULL_CODE',
      baselineMEWS: 0,
      allergies: ['Aspirin'],
      isolationStatus: 'NONE',
      isActive: true,
      history: ['Three-vessel CAD s/p CABG', 'Hypertension', 'Hyperlipidemia'],
    },
    bed: {
      id: 'BED-405',
      bedNumber: '405-A',
      wardId: 'WARD-4B',
      roomNumber: '405',
      status: 'OCCUPIED',
      currentPatientId: 'P005',
      cameraDeviceId: 'CAM-RPPG-405',
    },
    baselineVitals: {
      heartRate: 74,
      respiratoryRate: 16,
      systolicBP: 120,
      diastolicBP: 74,
      bodyTemperature: 36.9,
      oxygenSaturation: 98,
      hrvRmssd: 36,
      shockIndex: 0.62,
    },
    clinicalContext: {
      id: 'CTX-P005',
      patientId: 'P005',
      admissionReason: 'Cardiac Step-Down Ward Surveillance s/p CABG',
      postOpDay: 4,
      comorbidities: ['Ischemic Heart Disease', 'Hypertension'],
      codeStatus: 'FULL_CODE',
      oxygenDelivery: 'ROOM_AIR',
      isolationStatus: 'NONE',
      baselineMEWS: 0,
      updatedAt: REFERENCE_SHIFT_START,
    },
    initialLabs: [
      {
        id: 'LAB-P005-LAC',
        patientId: 'P005',
        timestamp: REFERENCE_SHIFT_START - 21600000,
        testCode: 'LACTATE',
        testName: 'Venous Lactate',
        value: 1.2,
        unit: 'MMOL_PER_L',
        referenceRange: { low: 0.5, high: 2.0 },
        isCritical: false,
        sourceLab: 'Central Hospital Lab',
      },
    ],
    clinicalNarrative: 'Post-sternotomy telemetry patient. Active in bed, prone to transient phone calls and position shifts.',
  },

  // --------------------------------------------------------------------------
  // Bed 406: High Respiratory Risk Patient (Severe CAP)
  // --------------------------------------------------------------------------
  {
    patient: {
      id: 'P006',
      mrn: 'MRN-40606',
      name: 'James Wilson',
      age: 73,
      gender: 'MALE',
      wardId: 'WARD-4B',
      bedId: 'BED-406',
      bedNumber: '406-B',
      admissionDiagnosis: 'Severe Community-Acquired Pneumonia (Right Middle & Lower Lobes)',
      admissionTimestamp: REFERENCE_SHIFT_START - 86400000,
      attendingPhysician: 'Dr. Michael Sterling, MD',
      primaryNurse: 'Nurse Rachel Hayes, RN',
      codeStatus: 'FULL_CODE',
      baselineMEWS: 3,
      allergies: ['Ciprofloxacin'],
      isolationStatus: 'DROPLET',
      isActive: true,
      history: ['Congestive Heart Failure NYHA II', 'Type 2 Diabetes', 'Peripheral Vascular Disease'],
    },
    bed: {
      id: 'BED-406',
      bedNumber: '406-B',
      wardId: 'WARD-4B',
      roomNumber: '406',
      status: 'OCCUPIED',
      currentPatientId: 'P006',
      cameraDeviceId: 'CAM-RPPG-406',
    },
    baselineVitals: {
      heartRate: 88,
      respiratoryRate: 22,
      systolicBP: 128,
      diastolicBP: 78,
      bodyTemperature: 38.2,
      oxygenSaturation: 92,
      hrvRmssd: 20,
      shockIndex: 0.69,
    },
    clinicalContext: {
      id: 'CTX-P006',
      patientId: 'P006',
      admissionReason: 'Severe Lobar Pneumonia with Hypoxemic Respiratory Distress',
      comorbidities: ['CHF NYHA II', 'Type 2 Diabetes', 'Hypertension'],
      codeStatus: 'FULL_CODE',
      oxygenDelivery: 'VENTURI_MASK',
      o2FlowRateLpm: 6.0,
      isolationStatus: 'DROPLET',
      baselineMEWS: 3,
      updatedAt: REFERENCE_SHIFT_START,
    },
    initialLabs: [
      {
        id: 'LAB-P006-LAC',
        patientId: 'P006',
        timestamp: REFERENCE_SHIFT_START - 14400000,
        testCode: 'LACTATE',
        testName: 'Venous Lactate',
        value: 2.1,
        unit: 'MMOL_PER_L',
        referenceRange: { low: 0.5, high: 2.0 },
        isCritical: true,
        sourceLab: 'Central Hospital Lab',
      },
      {
        id: 'LAB-P006-WBC',
        patientId: 'P006',
        timestamp: REFERENCE_SHIFT_START - 14400000,
        testCode: 'WBC',
        testName: 'White Blood Cell Count',
        value: 14.8,
        unit: 'X10_9_PER_L',
        referenceRange: { low: 4.0, high: 11.0 },
        isCritical: true,
        sourceLab: 'Central Hospital Lab',
      },
    ],
    clinicalNarrative: 'Frail elderly pneumonia patient with elevated work of breathing on Venturi mask. High risk of decompensation.',
  },
];
