import React, { useState } from 'react';
import {
  Copy,
  Check,
  Printer,
} from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import type { WardPatientRadarState } from '../types/radar';

interface SbarModalProps {
  isOpen: boolean;
  onClose: () => void;
  patient: WardPatientRadarState;
}

export const SbarModal: React.FC<SbarModalProps> = ({
  isOpen,
  onClose,
  patient,
}) => {
  const [isCopied, setIsCopied] = useState(false);

  // Derive SBAR text content
  const situation = `Bed ${patient.bedNumber} (${patient.name}, ${patient.age}y ${patient.gender}, MRN: ${patient.mrn}) is currently classified as ${patient.category.replace('_', ' ')} (Rank #${patient.categoryRank}, Attention Priority Score ${patient.apsScore}/100). Primary deterioration trigger: ${patient.whyNowSummary}`;

  const background = `Admitted for ${patient.admissionDiagnosis}. Attending Physician: ${patient.attendingPhysician}. Post-Op Day: #${patient.clinicalContext.postOpDay}. Code Status: ${patient.codeStatus}. Known Allergies: ${patient.allergies.length ? patient.allergies.join(', ') : 'No Known Drug Allergies (NKDA)'}. Comorbidities: ${patient.clinicalContext.comorbidities.join(', ')}.`;

  const assessment = `Hemodynamic State:
- Heart Rate: ${patient.vitals.heartRate} bpm (Baseline: ${patient.vitals.heartRateBaseline} bpm, Δ ${patient.vitals.heartRate - patient.vitals.heartRateBaseline >= 0 ? '+' : ''}${patient.vitals.heartRate - patient.vitals.heartRateBaseline} bpm)
- Blood Pressure: ${patient.vitals.systolicBP}/${patient.vitals.diastolicBP} mmHg (MAP: ${patient.vitals.meanArterialPressure} mmHg)
- Shock Index: ${patient.vitals.shockIndex.toFixed(2)} (Threshold: ≥0.70 abnormal, ≥1.00 critical)
- Respiratory Rate: ${patient.vitals.respiratoryRate} /min (Baseline: ${patient.vitals.respiratoryRateBaseline} /min)
- SpO2: ${patient.vitals.spo2}% on ${patient.vitals.oxygenDelivery}
- Subbe MEWS Score: ${patient.mews.totalScore} / 14 points
- Singer qSOFA Criteria: ${patient.qsofa?.criteriaMet || 0} / 3 criteria met
- Optical Signal Quality: ${patient.signalQuality.confidencePercent}% confidence (${patient.signalQuality.snrDb} dB)
- Information Freshness: Last verified ${patient.lastTrustedElapsedMinutes}m ago`;

  const recommendation = `1. Immediate bedside physical evaluation and manual blood pressure verification.
2. Consider IV fluid bolus (500 mL normal saline) and review surgical wound / drain output.
3. Review urgent repeat hemoglobin and serum lactate.
4. Urgent surgical registrar / Medical Emergency Team bedside consultation.`;

  const fullSbarMarkdown = `## CLINICAL SBAR HANDOFF BRIEF
**Generated by AegisPulse Attention Engine** | ${new Date().toLocaleString()}

### S - SITUATION
${situation}

### B - BACKGROUND
${background}

### A - ASSESSMENT
${assessment}

### R - RECOMMENDATION
${recommendation}

---
*Signed by Primary Nurse: ${patient.primaryNurse}*`;

  const handleCopy = () => {
    navigator.clipboard.writeText(fullSbarMarkdown);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent onClose={onClose} className="max-w-2xl max-h-[90vh] overflow-y-auto p-6 font-sans">
        <DialogHeader className="border-b border-border/40 pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="p-1.5 rounded-xl bg-white/80 dark:bg-slate-900/80 border border-border/70 shadow-xs flex items-center justify-center">
                <img src="/aegis-logo.png" alt="AegisPulse" className="h-7 w-7 object-contain" />
              </div>
              <div>
                <DialogTitle className="text-base font-bold text-foreground flex items-center gap-2">
                  Structured SBAR Handoff Dossier
                  <Badge variant="outline" className="font-mono text-[10px]">
                    Bed {patient.bedNumber}
                  </Badge>
                </DialogTitle>
                <DialogDescription className="text-xs text-muted-foreground mt-0.5">
                  AegisPulse Medical Emergency Team (MET) & Resident Briefing
                </DialogDescription>
              </div>
            </div>

            <Badge
              variant={patient.category === 'CRITICAL_REVIEW' ? 'destructive' : 'evaluate'}
              className="font-mono text-[10px] uppercase font-bold"
            >
              APS {patient.apsScore}/100
            </Badge>
          </div>
        </DialogHeader>

        {/* SBAR STRUCTURED SECTIONS */}
        <div className="space-y-3.5 py-2 text-xs">
          {/* Situation */}
          <div className="rounded-xl border border-border/70 bg-card p-4 space-y-1.5 shadow-xs border-l-4 border-l-rose-500">
            <div className="flex items-center justify-between">
              <span className="font-mono font-bold uppercase tracking-wider text-rose-600 dark:text-rose-400">
                S — Situation
              </span>
              <span className="text-[10px] font-mono text-muted-foreground">Urgent Deterioration</span>
            </div>
            <p className="text-foreground leading-relaxed font-medium">{situation}</p>
          </div>

          {/* Background */}
          <div className="rounded-xl border border-border/70 bg-card p-4 space-y-1.5 shadow-xs border-l-4 border-l-primary">
            <span className="font-mono font-bold uppercase tracking-wider text-primary">
              B — Background
            </span>
            <p className="text-foreground leading-relaxed">{background}</p>
          </div>

          {/* Assessment */}
          <div className="rounded-xl border border-border/70 bg-card p-4 space-y-1.5 shadow-xs border-l-4 border-l-amber-500">
            <div className="flex items-center justify-between">
              <span className="font-mono font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400">
                A — Assessment (Trajectories & Rules)
              </span>
              <span className="text-[10px] font-mono text-muted-foreground">Deterministic Provenance</span>
            </div>
            <pre className="text-foreground text-[11px] font-mono whitespace-pre-wrap leading-relaxed bg-muted/50 p-3 rounded-lg border border-border/50">
              {assessment}
            </pre>
          </div>

          {/* Recommendation */}
          <div className="rounded-xl border border-border/70 bg-card p-4 space-y-1.5 shadow-xs border-l-4 border-l-emerald-500">
            <span className="font-mono font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">
              R — Recommendation
            </span>
            <div className="text-foreground space-y-1 pl-1">
              <p>1. Immediate bedside physical evaluation and manual cuff blood pressure check.</p>
              <p>2. Consider 500 mL normal saline IV fluid challenge; evaluate surgical site.</p>
              <p>3. Send stat repeat hemoglobin and arterial blood gas / serum lactate.</p>
              <p>4. On-call registrar / RRT immediate bedside review.</p>
            </div>
          </div>
        </div>

        {/* FOOTER ACTIONS */}
        <div className="border-t border-border/40 pt-4 flex items-center justify-between gap-3 flex-wrap">
          <div className="text-[11px] font-mono text-muted-foreground flex items-center gap-1.5">
            <img src="/aegis-logo.png" alt="AegisPulse" className="h-3.5 w-3.5 object-contain" />
            <span>AegisPulse SBAR • Lead Nurse: <strong className="text-foreground">{patient.primaryNurse}</strong></span>
          </div>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="text-xs font-mono gap-1"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print Brief</span>
            </Button>

            <Button
              variant="default"
              size="sm"
              onClick={handleCopy}
              className="gap-1.5 text-xs font-bold font-mono"
            >
              {isCopied ? <Check className="h-4 w-4 text-emerald-300" /> : <Copy className="h-4 w-4" />}
              <span>{isCopied ? 'Copied to Clipboard!' : 'Copy SBAR'}</span>
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
